### ISSUE TITLE
put leaderboard somewhere private

### ISSUE THREAD

**Issue by judithabk6** [DeveauP/DREAM#7]

**Comment by judithabk6** [comment]
I thought synapse would be a good option. This way, we can update the leaderboard directly from the validation script. 
Juste one drawback, creating content on synapse (e.g. uploading a file, I do not know about updating an existing file) requires to be a "certified" user. To be certified, there is a small quizz to take...

**Comment by DeveauP** [comment]
J'ai passé le test : )
